palette = "vibes"

[palettes.vibes]
red = "#f7768e"
amber = "#e0af68"
blue = "#7dcfff"
purple = "#bb9af7"
green = "#73daca"
gray = "#3b4261"

format = """
$directory$git_branch$git_commit$git_state$git_metrics$git_status$gcloud$aws$azure$fill$cmd_duration
  $character"""

[fill]
symbol = '-'
style = 'fg:8'

[character]
success_symbol = "[ ](bold 2)"
error_symbol = "[ ](bold 1)"

[package]
disabled = true

[git_branch]
style = "bold 3"
symbol = "󰘬"
truncation_symbol = "…"
format = " [$symbol $branch(:$remote_branch)]($style) "

[git_commit]
commit_hash_length = 4
tag_symbol = " "
only_detached = true

[git_state]
format = ' [\($state( $progress_current/$progress_total)\)](bold 1) '
cherry_pick = "[󰘬 PICK](red bold)"
rebase = "[󰘬 REBASE](amber bold)"
merge = "[󰘬 MERGE](blue bold)"
bisect = "[ BISECT](purple bold)"
revert = "[ REVERT](red bold)"
am = "[ AM](amber bold)"
style = "amber bold"

[git_status]
format = '([$ahead_behind]($style))([$all_status]($style)) '

ahead      = "[ 󰮣 $count](green bold)"
behind     = "[ 󰮥 $count](red bold)"
diverged   = "[ 󱡦 ${ahead_count}↑${behind_count}↓](amber bold)"
up_to_date = "[ 󰄬](gray)"

staged     = "[  $count](green)"
modified   = "[  $count](amber)"
deleted    = "[  $count](red)"
untracked  = "[  $count](gray)"
renamed    = "[  $count](blue)"
stashed    = "[ 󰏗 ](purple)"
conflicted = "[ 󰅖 $count](red bold)"
style = "amber bold"

[git_metrics]
added_style        = 'green'
deleted_style      = 'red'
format             = '([+$added]($added_style))([-$deleted]($deleted_style))'
only_nonzero_diffs = true
disabled           = false

[hostname]
ssh_only = true
format =  "[@$hostname](bold 4) "
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed 2"

[time]
disabled = true
format = '🕙[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold 5"
style_root = "bold 1"
format = "[$user]($style) "
disabled = false

[directory]
home_symbol = " "
read_only = "  "
style = "bold 6"
truncation_length = 2
truncation_symbol = "../"
format = '  [󰉋  $path]($style) '

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"code" = "  "

[cmd_duration]
min_time = 0
format = ' [󱑌 $duration](gray)'

[gcloud]
format = ' [$symbol](gray)'
symbol = ' '
disabled = false

[aws]
format = ' [$symbol](gray)'
symbol = ' '
disabled = false

[azure]
format = ' [$symbol](gray)'
symbol = '󰠅 '
disabled = false
