exec-once = Telegram -startintray
exec-once = discord --start-minimized
exec-once = [workspace special:magic silent] env QT_QPA_PLATFORM=xcb fdm
exec-once = tailscale-systray
exec-once = tomate-gtk
exec-once = arch-update --tray

exec-once = [workspace 6 silent] betterbird
exec-once = [workspace 7 silent] kitty btop

