gesture = 4, horizontal, unset
gesture = 4, up, unset
gesture = 4, down, unset
gesture = 3, swipe, unset

gesture = 3, horizontal, workspace
gesture = 3, up, dispatcher, global, quickshell:overviewToggle
gesture = 3, down, dispatcher, global, quickshell:overviewClose
gesture = 4, swipe, move
